
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.liveramp.databases.workflow_db.iface;

import com.liveramp.databases.workflow_db.models.WorkflowAlertWorkflowExecution;
import com.liveramp.databases.workflow_db.query.WorkflowAlertWorkflowExecutionQueryBuilder;
import com.liveramp.databases.workflow_db.query.WorkflowAlertWorkflowExecutionDeleteBuilder;

import java.io.IOException;
import java.util.Map;
import java.util.List;

import com.rapleaf.jack.IModelPersistence;

public interface IWorkflowAlertWorkflowExecutionPersistence extends IModelPersistence<WorkflowAlertWorkflowExecution> {
  WorkflowAlertWorkflowExecution create(final long workflow_alert_id, final long workflow_execution_id) throws IOException;

  WorkflowAlertWorkflowExecution createDefaultInstance() throws IOException;
  List<WorkflowAlertWorkflowExecution> findByWorkflowAlertId(long value)  throws IOException;
  List<WorkflowAlertWorkflowExecution> findByWorkflowExecutionId(long value)  throws IOException;

  WorkflowAlertWorkflowExecutionQueryBuilder query();

  WorkflowAlertWorkflowExecutionDeleteBuilder delete();
}
