#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require File.join File.dirname(__FILE__), 'audience_types'

module Liveramp
  module Audience
    MATCHING_ACCURACY_TYPE_DETERMINISTIC_NAME = %q"deterministic"

    LEGACY_ONLINE_NAME = %q"legacy_online"

  end
end
