#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require File.join File.dirname(__FILE__), 'auto_exposure_matching_types'

module Liveramp
  module Types
    module AutoExposureMatching
    end
  end
end
