#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require File.join File.dirname(__FILE__), 'destination_stats_processor_types'

module Liveramp
  module LogStats
    module DestinationStatsProcessor
    end
  end
end
