#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require File.join File.dirname(__FILE__), 'partner_link_fast_lane_types'

module Liveramp
  module Types
    module PartnerLinkFastLane
    end
  end
end
