#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require File.join File.dirname(__FILE__), 'bang_types'
require File.join File.dirname(__FILE__), 'anonymous_identifier_mapping_types'


module Liveramp
  module Types
    module PartnerLinkFastLane
      module FastLaneImportStatus
        PENDING = 1
        IN_PROGRESS = 2
        COMPLETED = 3
        CANCELLED = 4
        FAILED = 5
        NOT_FAST_LANE = 6
        DELETED = 7
        VALUE_MAP = {1 => "PENDING", 2 => "IN_PROGRESS", 3 => "COMPLETED", 4 => "CANCELLED", 5 => "FAILED", 6 => "NOT_FAST_LANE", 7 => "DELETED"}
        VALID_VALUES = Set.new([PENDING, IN_PROGRESS, COMPLETED, CANCELLED, FAILED, NOT_FAST_LANE, DELETED]).freeze
      end

    end
  end
end
