#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module Liveramp
  module Types
    module Workflow
      module Test
        class Email; end

        class TestType; end

        class Email
          include ::Thrift::Struct, ::Thrift::Struct_Union
          EMAIL = 1

          FIELDS = {
            EMAIL => {:type => ::Thrift::Types::STRING, :name => 'email'}
          }

          def struct_fields; FIELDS; end

          def validate
            raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field email is unset!') unless @email
          end

          ::Thrift::Struct.generate_accessors self
        end

        class TestType
          include ::Thrift::Struct, ::Thrift::Struct_Union
          TEST = 1

          FIELDS = {
            TEST => {:type => ::Thrift::Types::STRING, :name => 'test'}
          }

          def struct_fields; FIELDS; end

          def validate
            raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field test is unset!') unless @test
          end

          ::Thrift::Struct.generate_accessors self
        end

      end
    end
  end
end
