#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'spruce_lib_service_types'

module Rapleaf
  module SpruceLib
    module SpruceLibService
    end
  end
end
