/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.liveramp.databases.workflow_db.query;

import java.util.Collection;

import com.rapleaf.jack.queries.AbstractQueryBuilder;
import com.rapleaf.jack.queries.Column;
import com.rapleaf.jack.queries.FieldSelector;
import com.rapleaf.jack.queries.where_operators.IWhereOperator;
import com.rapleaf.jack.queries.where_operators.JackMatchers;
import com.rapleaf.jack.queries.WhereConstraint;
import com.rapleaf.jack.queries.QueryOrder;
import com.rapleaf.jack.queries.OrderCriterion;
import com.rapleaf.jack.queries.LimitCriterion;
import com.liveramp.databases.workflow_db.iface.IWorkflowAlertPersistence;
import com.liveramp.databases.workflow_db.models.WorkflowAlert;


public class WorkflowAlertQueryBuilder extends AbstractQueryBuilder<WorkflowAlert> {

  public WorkflowAlertQueryBuilder(IWorkflowAlertPersistence caller) {
    super(caller);
  }

  public WorkflowAlertQueryBuilder select(WorkflowAlert._Fields... fields) {
    for (WorkflowAlert._Fields field : fields){
      addSelectedField(new FieldSelector(field));
    }
    return this;
  }

  public WorkflowAlertQueryBuilder selectAgg(FieldSelector... aggregatedFields) {
    addSelectedFields(aggregatedFields);
    return this;
  }

  public WorkflowAlertQueryBuilder id(Long value) {
    addId(value);
    return this;
  }

  public WorkflowAlertQueryBuilder idIn(Collection<Long> values) {
    addIds(values);
    return this;
  }

  public WorkflowAlertQueryBuilder whereId(IWhereOperator<Long> operator) {
    addWhereConstraint(new WhereConstraint<>(Column.fromId(null), operator, null));
    return this;
  }

  public WorkflowAlertQueryBuilder limit(int offset, int nResults) {
    setLimit(new LimitCriterion(offset, nResults));
    return this;
  }

  public WorkflowAlertQueryBuilder limit(int nResults) {
    setLimit(new LimitCriterion(nResults));
    return this;
  }

  public WorkflowAlertQueryBuilder groupBy(WorkflowAlert._Fields... fields) {
    addGroupByFields(fields);
    return this;
  }

  public WorkflowAlertQueryBuilder order() {
    this.addOrder(new OrderCriterion(QueryOrder.ASC));
    return this;
  }

  public WorkflowAlertQueryBuilder order(QueryOrder queryOrder) {
    this.addOrder(new OrderCriterion(queryOrder));
    return this;
  }

  public WorkflowAlertQueryBuilder orderById() {
    this.addOrder(new OrderCriterion(QueryOrder.ASC));
    return this;
  }

  public WorkflowAlertQueryBuilder orderById(QueryOrder queryOrder) {
    this.addOrder(new OrderCriterion(queryOrder));
    return this;
  }

  public WorkflowAlertQueryBuilder alertClass(String value) {
    addWhereConstraint(new WhereConstraint<>(WorkflowAlert._Fields.alert_class, JackMatchers.equalTo(value)));
    return this;
  }

  public WorkflowAlertQueryBuilder whereAlertClass(IWhereOperator<String> operator) {
    addWhereConstraint(new WhereConstraint<>(WorkflowAlert._Fields.alert_class, operator));
    return this;
  }

  public WorkflowAlertQueryBuilder orderByAlertClass() {
    this.addOrder(new OrderCriterion(WorkflowAlert._Fields.alert_class, QueryOrder.ASC));
    return this;
  }

  public WorkflowAlertQueryBuilder orderByAlertClass(QueryOrder queryOrder) {
    this.addOrder(new OrderCriterion(WorkflowAlert._Fields.alert_class, queryOrder));
    return this;
  }

  public WorkflowAlertQueryBuilder message(String value) {
    addWhereConstraint(new WhereConstraint<>(WorkflowAlert._Fields.message, JackMatchers.equalTo(value)));
    return this;
  }

  public WorkflowAlertQueryBuilder whereMessage(IWhereOperator<String> operator) {
    addWhereConstraint(new WhereConstraint<>(WorkflowAlert._Fields.message, operator));
    return this;
  }

  public WorkflowAlertQueryBuilder orderByMessage() {
    this.addOrder(new OrderCriterion(WorkflowAlert._Fields.message, QueryOrder.ASC));
    return this;
  }

  public WorkflowAlertQueryBuilder orderByMessage(QueryOrder queryOrder) {
    this.addOrder(new OrderCriterion(WorkflowAlert._Fields.message, queryOrder));
    return this;
  }
}
