
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.liveramp.databases.workflow_db.iface;

import com.liveramp.databases.workflow_db.models.StepDependency;
import com.liveramp.databases.workflow_db.query.StepDependencyQueryBuilder;
import com.liveramp.databases.workflow_db.query.StepDependencyDeleteBuilder;

import java.io.IOException;
import java.util.Map;
import java.util.List;

import com.rapleaf.jack.IModelPersistence;

public interface IStepDependencyPersistence extends IModelPersistence<StepDependency> {
  StepDependency create(final long step_attempt_id, final long dependency_attempt_id) throws IOException;

  StepDependency createDefaultInstance() throws IOException;
  List<StepDependency> findByStepAttemptId(long value)  throws IOException;
  List<StepDependency> findByDependencyAttemptId(long value)  throws IOException;

  StepDependencyQueryBuilder query();

  StepDependencyDeleteBuilder delete();
}
