
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.liveramp.databases.workflow_db.iface;

import com.liveramp.databases.workflow_db.models.StepAttempt;
import com.liveramp.databases.workflow_db.query.StepAttemptQueryBuilder;
import com.liveramp.databases.workflow_db.query.StepAttemptDeleteBuilder;

import java.io.IOException;
import java.util.Map;
import java.util.List;

import com.rapleaf.jack.IModelPersistence;

public interface IStepAttemptPersistence extends IModelPersistence<StepAttempt> {
  StepAttempt create(final int workflow_attempt_id, final String step_token, final Long start_time, final Long end_time, final int step_status, final String failure_cause, final String failure_trace, final String action_class, final String status_message) throws IOException;
  StepAttempt create(final int workflow_attempt_id, final String step_token, final int step_status, final String action_class) throws IOException;

  StepAttempt createDefaultInstance() throws IOException;
  List<StepAttempt> findByWorkflowAttemptId(int value)  throws IOException;
  List<StepAttempt> findByStepToken(String value)  throws IOException;
  List<StepAttempt> findByStartTime(Long value)  throws IOException;
  List<StepAttempt> findByEndTime(Long value)  throws IOException;
  List<StepAttempt> findByStepStatus(int value)  throws IOException;
  List<StepAttempt> findByFailureCause(String value)  throws IOException;
  List<StepAttempt> findByFailureTrace(String value)  throws IOException;
  List<StepAttempt> findByActionClass(String value)  throws IOException;
  List<StepAttempt> findByStatusMessage(String value)  throws IOException;

  StepAttemptQueryBuilder query();

  StepAttemptDeleteBuilder delete();
}
