# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'
require File.expand_path('../lib/workflow_db', __FILE__)

WorkflowDb::Application.load_tasks

gem_root = Gem.loaded_specs['db_support'].full_gem_path
load "#{gem_root}/lib/tasks/rapleaf.rake"
load "#{gem_root}/lib/tasks/cruise.rake"

