
source 'https://rubygems.org' do

  gem 'rails', '4.2.11.1'
  gem 'mysql2', '0.3.21'
  gem 'thrift', '0.11.0'
  gem 'activerecord', '4.2.11.1'
  gem 'workflow2_types', '1.0.4'
  gem 'json', '1.8.6'

end